# Generated by Django 3.1.1 on 2020-09-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_owner'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arts',
            field=models.ManyToManyField(related_name='art', to='art.Art'),
        ),
    ]
