# Generated by Django 3.1.1 on 2020-09-11 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_art_owner'),
        ('jwt_auth', '0002_user_arts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='arts',
        ),
        migrations.AddField(
            model_name='user',
            name='arts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art', to='art.art'),
        ),
    ]
