# Generated by Django 3.1.1 on 2020-09-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0003_auto_20200911_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='arts',
        ),
    ]
