# Generated by Django 3.1.1 on 2020-09-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_types', '0002_auto_20200912_1046'),
        ('jwt_auth', '0004_remove_user_arts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='types',
            field=models.ManyToManyField(related_name='users', to='artist_types.Type'),
        ),
    ]
