# Generated by Django 3.1.1 on 2020-09-12 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0005_user_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
