# Generated by Django 3.1.1 on 2020-09-13 11:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist_types', '0002_auto_20200912_1046'),
        ('jwt_auth', '0006_user_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='users', to='artist_types.Type'),
        ),
    ]
