# Generated by Django 3.1.1 on 2020-09-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0007_auto_20200913_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
